// Generated by: npx supabase gen types typescript --linked > types/database.ts
// Re-run after every schema change to keep types in sync with the database
//
// PLACEHOLDER: This file was hand-written to match supabase/migrations/001_initial_schema.sql
// Replace with the real generated types after running:
//   npx supabase login
//   npx supabase link --project-ref YOUR_PROJECT_REF
//   npx supabase gen types typescript --linked > types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          user_id: string | null
          store_name: string
          operator: string | null
          company_code: string | null
          category: string | null
          space_m2: number | null
          rent_eur: number | null
          created_at: string | null
        }
        Insert: {
          id?: string
          user_id?: string | null
          store_name: string
          operator?: string | null
          company_code?: string | null
          category?: string | null
          space_m2?: number | null
          rent_eur?: number | null
          created_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string | null
          store_name?: string
          operator?: string | null
          company_code?: string | null
          category?: string | null
          space_m2?: number | null
          rent_eur?: number | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tenants_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      revenue_reports: {
        Row: {
          id: string
          user_id: string | null
          tenant_id: string | null
          month: string
          amount_eur: number
          tx_count: number | null
          submitted_at: string | null
        }
        Insert: {
          id?: string
          user_id?: string | null
          tenant_id?: string | null
          month: string
          amount_eur: number
          tx_count?: number | null
          submitted_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string | null
          tenant_id?: string | null
          month?: string
          amount_eur?: number
          tx_count?: number | null
          submitted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "revenue_reports_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "revenue_reports_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          }
        ]
      }
      faq_items: {
        Row: {
          id: string
          question: string
          answer: string
          sort_order: number | null
          created_at: string | null
        }
        Insert: {
          id?: string
          question: string
          answer: string
          sort_order?: number | null
          created_at?: string | null
        }
        Update: {
          id?: string
          question?: string
          answer?: string
          sort_order?: number | null
          created_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Convenience type aliases for common usage patterns
export type Tenant = Database['public']['Tables']['tenants']['Row']
export type TenantInsert = Database['public']['Tables']['tenants']['Insert']
export type TenantUpdate = Database['public']['Tables']['tenants']['Update']

export type RevenueReport = Database['public']['Tables']['revenue_reports']['Row']
export type RevenueReportInsert = Database['public']['Tables']['revenue_reports']['Insert']
export type RevenueReportUpdate = Database['public']['Tables']['revenue_reports']['Update']

export type FaqItem = Database['public']['Tables']['faq_items']['Row']
export type FaqItemInsert = Database['public']['Tables']['faq_items']['Insert']
export type FaqItemUpdate = Database['public']['Tables']['faq_items']['Update']
