import type { PromoItem } from '@/components/marketing/promo-card'

export const PROMO_ITEMS: PromoItem[] = [
  {
    id: 'rieker',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-1.jpg',
    title: 'Papildoma nuolaida Rieker!',
    date: 'Nuo 2026.03.25 iki 2026.03.29',
    href: '/akcijos/rieker',
    category: 'stores',
  },
  {
    id: 'pavasaris',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-2.jpg',
    title: 'Kvepia pavasariu',
    date: 'Nuo 2026.03.25 iki 2026.03.29',
    href: '/akcijos/pavasaris',
    category: 'stores',
  },
  {
    id: 'samsung',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-3.jpg',
    title: 'Samsung naujienos',
    date: 'Nuo 2026.03.25 iki 2026.03.29',
    href: '/akcijos/samsung',
    category: 'stores',
  },
  {
    id: 'vision-express',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-4.jpg',
    title: 'Vision Express akcija',
    date: 'Nuo 2026.03.25 iki 2026.03.29',
    href: '/akcijos/vision-express',
    category: 'services',
  },
  {
    id: 'lindex',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-1.jpg',
    title: 'Nauja kolekcija Lindex',
    date: 'Nuo 2026.04.01 iki 2026.04.14',
    href: '/akcijos/lindex',
    category: 'stores',
  },
  {
    id: 'vasara',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-2.jpg',
    title: 'Vasaros išpardavimas',
    date: 'Nuo 2026.06.01 iki 2026.06.30',
    href: '/akcijos/vasara',
    category: 'stores',
  },
  {
    id: 'sportas',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-3.jpg',
    title: 'Sporto prekių nuolaidos',
    date: 'Nuo 2026.05.15 iki 2026.05.31',
    href: '/akcijos/sportas',
    category: 'services',
  },
  {
    id: 'caffeine',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-4.jpg',
    title: 'Caffeine kavos diena',
    date: 'Nuo 2026.06.10 iki 2026.06.10',
    href: '/akcijos/caffeine',
    category: 'food',
  },
  {
    id: 'iki',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-1.jpg',
    title: 'IKI maisto akcija',
    date: 'Nuo 2026.06.05 iki 2026.06.11',
    href: '/akcijos/iki',
    category: 'food',
  },
  {
    id: 'miyako',
    image: 'https://hfnsbhovdjqnfzjpugwa.supabase.co/storage/v1/object/public/marketing-assets/news-2.jpg',
    title: 'Miyako sushi akcija',
    date: 'Nuo 2026.06.01 iki 2026.06.07',
    href: '/akcijos/miyako',
    category: 'food',
  },
]
